spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CSPOP-BACKEND?autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true