spring:
  datasource:
    url: ${SOURCE_MYSQL_URL}
    username: ${SOURCE_MYSQL_USERNAME}
    password: ${SOURCE_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 500
  sql:
    init:
      mode: always
      data-locations: classpath:sql/init.sql, classpath:sql/data.sql

jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    expire-length: 3600000